### ISSUE TITLE
Garden Schema

### ISSUE THREAD

**Issue by NestorJMartinez** [hack4impact-calpoly/naacp#1]
### Todo

- Research Typescript
- Create a Garden schema Typescript file with the following format
  - name: String
  - description: String
  - location: String
  - pictures: [String]
  - gardeners: [String]
  - community: Boolean
  - plants: [String]
  - date: Date
  - requested: [String]

### Checklist

- [x] Research Typescript (Nothing too specific just get familiar with how it's different from Javascript)

- [x] Create ./backend/models/garden.ts

- [x] Match the model with the same format as the description

Make sure to add the issue number to the pull request comment and to add @NestorJMartinez as the reviewer
