### ISSUE TITLE
Create Forgot Password Page

### ISSUE THREAD

**Issue by NestorJMartinez** [hack4impact-calpoly/naacp#18]
### Todo
- Create the Forgot Password Page from Figma
  - Don't worry about installation or configuration, I'll take care of that
  - Using AWS Amplify Authentication, implement the UI components to create the forgot password page

### Checklist
- [ ] Create `./frontend/src/components/ForgotPasswordPage/ForgotPasswordPage.tsx`
- [ ] Using the UI components, from AWS Amplify Authentication, implement the Forgot Password page
- [ ] Looks exactly like the Figma

### Resources
Here are the [AWS Amplify docs](https://docs.amplify.aws/lib/auth/getting-started/q/platform/js/#enable-sign-up-sign-in-and-sign-out) 

Make sure to add the issue number to the pull request comment and to add @NestorJMartinez as the reviewer
