### ISSUE TITLE
Connecting to MongoDB

### ISSUE THREAD

**Issue by NestorJMartinez** [hack4impact-calpoly/naacp#2]
### Todo

- Research Typescript
- Connect to both of our MongoDB databases
  - This'll be different from Bootcamp because we'll be connecting to two databases at once
  - Install the mongoose package in ./backend
  - Install the dotenv package in ./backend to allow us to use environment files
     - You can follow the Install and Usage sections of this ReadMe https://www.npmjs.com/package/dotenv
  - Make two variables in ./backend/.env and assign it to the MongoDB links found on Slack
    - gardenDB="insert link here"
    - userDB="insert link here"
  - Write the connection code in ./backend/connection.ts

### Checklist

- [x] Research Typescript (Nothing too specific just get familiar with how it's different from Javascript)
- [x] Download Mongoose package
- [x] Download dotenv
- [x] Create gardenDB variable in .env
- [x] Create userDB variable in .env
- [x] Successfully connect to our MongoDB databases in connection.ts

### Resources
Here's an [article](https://dev.to/ziishaned/open-multiple-mongodb-connection-in-express-js-app-36be) that can help, only work on the connection.ts file don't worry about the models for now

Doing this is a little weird so if you need any help let me know, I've done this in the past
Make sure to add the issue number to the pull request comment and to add @NestorJMartinez as the reviewer
