### ISSUE TITLE
More User endpoints

### ISSUE THREAD

**Issue by NestorJMartinez** [hack4impact-calpoly/naacp#21]
### Todo

- Rename the current `/api/users` endpoint to `/users`
- Add some more User endpoints in "./backend/server.ts"
  - GET `/users/:id` 
     - Returns a User with the provided id in the request body
  - POST `/users`
    - Adds a User to MongoDB 
    - Data for the User is provided in the request body
- Add try catch blocks to all endpoints
  - This'll help to make sure we're covering any error if they pop up
  - If any errors are caught you can send the response status as 400
### Checklist
- [ ] Rename `/api/users` to `/users`
- [ ] Add a GET endpoint `/users/:id` that gets a User given their id
- [ ] Add a POST endpoint `/users` that creates a User given their id
- [ ] Add try catch blocks
- [ ] Make sure to test it with Postman

### Notes
The data in MongoDB should now be accessible to test with in Postman, but we're still working on replacing the values with actual test data

Make sure to add the issue number to the pull request comment and to add @NestorJMartinez as the reviewer
