### ISSUE TITLE
More Garden endpoints

### ISSUE THREAD

**Issue by NestorJMartinez** [hack4impact-calpoly/naacp#25]
### Todo
- Add some Garden endpoints in "./backend/server.ts"
  - GET `/gardens/:id` 
     - Returns a Garden with the provided id in the request body
  - POST `/gardens`
    - Adds a Garden to MongoDB 
    - Data for the Garden is provided in the request body
- Add try catch blocks to all endpoints
  - This'll help to make sure we're covering any error if they pop up
  - If any errors are caught you can send the response status as 400
### Checklist
- [x] Add a GET endpoint `/gardens/:id` that gets a User given their id
- [x] Add a POST endpoint `/gardens` that creates a User given their id
- [x] Add try catch blocks
- [x] Make sure to test it with Postman

### Notes
The data in MongoDB should now be accessible to test with in Postman, but we're still working on replacing the values with actual test data

Make sure to add the issue number to the pull request comment and to add @NestorJMartinez as the reviewer
