### ISSUE TITLE
Update Gardener endpoints

### ISSUE THREAD

**Issue by NestorJMartinez** [hack4impact-calpoly/naacp#28]
### Todo
- Add a Garden endpoint in "./backend/server.ts"
  - PUT `/gardens/:id` 
     - Updates a Garden
     - Data for the Garden is provided in the request body
- Add try catch blocks to all endpoints
  - This'll help to make sure we're covering any error if they pop up
  - If any errors are caught you can send the response status as 400
- Write a test case for any endpoints you've written before [MOVED TO NEXT ISSUE]
  - More info will come out as I finish setting up our test framework, I'll let you know when it's ready
 
### Checklist
- [x] Add a PUT endpoint `/gardens/:id` that updates a Garden given its id
- [x] Add try catch blocks
- [ ] Write test cases

### Notes
Make sure to add the issue number to the pull request comment and to add @NestorJMartinez as the reviewer
