### ISSUE TITLE
PUT User endpoint and Unit Tests

### ISSUE THREAD

**Issue by NestorJMartinez** [hack4impact-calpoly/naacp#31]
### Todo
- Add a User endpoint in "./backend/server.ts"
  - PUT `/users/:id` 
     - Updates a User
     - Data for the User is provided in the request body
- Add try catch blocks to all endpoints
  - This'll help to make sure we're covering any error if they pop up
  - If any errors are caught you can send the response status as 400
- Write a test case for any endpoints you've written before
  - More info will come out as I finish setting up our test framework, I'll let you know when it's ready
 
### Checklist
- [ ] Add a PUT endpoint `/users/:id` that updates a Users given its id
- [ ] Add try catch blocks
- [ ] Write test cases

### Notes
Make sure to add the issue number to the pull request comment and to add @NestorJMartinez as the reviewer
