### ISSUE TITLE
Create the Footer

### ISSUE THREAD

**Issue by NestorJMartinez** [hack4impact-calpoly/naacp#37]
### Todo
- Learn Tailwind CSS
- Create the Footer from Figma
<img width="772" alt="Screen Shot 2022-03-09 at 7 33 04 PM" src="https://user-images.githubusercontent.com/43479997/157585547-8daef0ca-712e-4433-b71b-2e9535c3f301.png">

### Checklist
- [ ] Create `./frontend/src/components/Footer/Footer.tsx`
- [ ] Style it using Tailwind CSS
- [ ] Looks exactly like the Figma

### Resources
Here's [the Figma](https://www.figma.com/file/GksWg6xQg2NxNM67VvUBsD/NAACP-Wireframing?node-id=0%3A1) 

Make sure to add the issue number to the pull request comment and to add @NestorJMartinez as the reviewer
