### ISSUE TITLE
Create the Search Page

### ISSUE THREAD

**Issue by NestorJMartinez** [hack4impact-calpoly/naacp#38]
### Todo
- Create the Search Page from Figma
  - Connect the search bar with the database
  - Populate the results section with the Garden Cards, using results from the search bar and info from the database
  - Create the possible filters of people, garden, and location
    - Selecting these filers will change the possible results entered from the search bar
  - Connect the page with the header component, do not recreate the navbar
<img width="751" alt="Screen Shot 2022-04-01 at 7 08 02 PM" src="https://user-images.githubusercontent.com/43479997/161361630-f2b1c4f0-4070-484e-b6a2-8c39894538b9.png">

### Checklist
- [ ] Create `./frontend/src/components/SearchPage/SearchPage.tsx`
- [ ] Is styled exactly like the Figma
- [ ] Connect the page with the database
- [ ] Create the three filters

### Resources
[Figma link](https://www.figma.com/file/GksWg6xQg2NxNM67VvUBsD/NAACP-Wireframing?node-id=107%3A179)

Make sure to add the issue number to the pull request comment and to add @NestorJMartinez as the reviewer
