### ISSUE TITLE
Check Out AWS Amplify Authentication

### ISSUE THREAD

**Issue by NestorJMartinez** [hack4impact-calpoly/naacp#4]
### Todo
- Research Typescript
- Research AWS Authentication and how we can use it on the frontend 
  - You can find the docs [here](https://docs.amplify.aws/lib/auth/getting-started/q/platform/js/)
  - I'll take care of setting up AWS and AWS Amplify, I want you to look over how to code it into our frontend
  - I'm considering the pre-built UI Components, so try to give me an idea to see how easy/complicated it would to implement

### Checklist

- [ ] Research Typescript (Nothing too specific just get familiar with how it's different from Javascript)
- [ ] Get familiar with AWS Authentication
- [ ] Send me some info on pre-built UI components (how feasible it is, or if you think using API calls would be better)

Don't worry about making a pull request, just message me in Slack to let me know you're done
