### ISSUE TITLE
Add React Router

### ISSUE THREAD

**Issue by NestorJMartinez** [hack4impact-calpoly/naacp#5]
### Todo
- Research Typescript
- Setup Frontend Routing using react-router-dom
  - Install the package
  - Make two pages (Home and Login) and add routing to both in App.tsx

### Checklist

- [ ] Research Typescript (Nothing too specific just get familiar with how it's different from Javascript)
- [ ] Install the package react-router-dom in ./frontend
- [ ] Create ./frontend/src/components/Home/Home.tsx  
- [ ] Add a header tag with the text "home" in Home.tsx
- [ ] Create ./frontend/src/components/Login/Login.tsx
- [ ] Add a header tag with the text "Login" in Login.tsx
- [ ] Add routing to these components in App.tsx

### Resources
This [intro link](https://v5.reactrouter.com/web/guides/quick-start) could help get you started. 

Make sure to add the issue number to the pull request comment and to add @NestorJMartinez as the reviewer
