### ISSUE TITLE
Setup Tailwind CSS

### ISSUE THREAD

**Issue by NestorJMartinez** [hack4impact-calpoly/naacp#6]
### Todo

- Research Typescript
- Setup Tailwind CSS
  - Research Tailwind CSS
  - Follow [this article](https://tailwindcss.com/docs/guides/create-react-app) to set up Tailwind for our project
    - We already have step one, follow the rest of the steps in ./frontend

### Checklist

- [x] Research Typescript (Nothing too specific just get familiar with how it's different from Javascript)
- [x] Research Tailwind CSS (Get a basic understanding on what it does and how it's used)
- [x] Download the Tailwind package in ./frontend
- [x] Set up the config file
- [x] Add the directives to ./frontend/src/App.css

Make sure to add the issue number to the pull request comment and to add @NestorJMartinez as the reviewer
