### ISSUE TITLE
User Schema

### ISSUE THREAD

**Issue by NestorJMartinez** [hack4impact-calpoly/naacp#8]
### Todo

- Create a User schema Typescript file with the following format
  - first_name: String
  - last_name: String
  - description: String
  - phone: String
  - email: String
  - picture: String
  - gardens: [String]
  - saved: [String]
- We're using multiple connections to MongoDB, and since we're using Typescript this'll be different from bootcamp
   - Import the connections from ./backend/connection.ts
   - When exporting the model at the end of the file, you'll have something like this
      - `const User = userConnection.model('userDB', userSchema)`
 instead of the normal mongoose.model(...)
   - The collection name is "userDB"

### Checklist

- [x] Create ./backend/models/user.ts
- [x] Match the model with the same format as the description
- [x] Have the correct ".model"

### Resources
This [link](https://mongoosejs.com/docs/typescript.html) has a good template on how to do this. Remember to export the file, you might have to edit the connection.ts file to get it to work.

Make sure to add the issue number to the pull request comment and to add @NestorJMartinez as the reviewer
